- name: Update load-balancer.conf
  hosts: load_balancer
  become: yes  # Use sudo to gain root privileges
  tasks:
    - name: Replace references to http://pool2 with http://pool1
      replace:
        path: /etc/nginx/conf.d/load-balancer.conf
        regexp: 'http://pool2'
        replace: 'http://pool1'
      notify:
        - Reload nginx

handlers:
    - name: Reload nginx
      service:
        name: nginx
        state: reloaded